name: Update NBA dataset and publish to Kaggle

on:
  schedule:
    - cron: "0 12 * * *"    # 12:00 UTC daily (8:00 AM America/New_York)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          set -euxo pipefail
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install kaggle

      - name: Seed empty CSVs if missing (first-run safety)
        run: |
          set -euxo pipefail
          python - <<'PY'
          import os, csv
          os.makedirs('export', exist_ok=True)
          def ensure(path, cols):
              if not os.path.exists(path):
                  with open(path,'w',newline='',encoding='utf-8') as f:
                      csv.writer(f).writerow(cols)
          games_cols = ["gameId","gameCode","gameDateEt","gameStatusText","period","gameClock","arenaName",
                        "homeTeamId","homeTeamTricode","homeScore","awayTeamId","awayTeamTricode","awayScore"]
          players_cols = ["gameId","playerId","teamId","teamTricode","firstName","familyName","jerseyNum","position",
                          "minutes","points","reboundsTotal","assists","steals","blocks","turnovers",
                          "fieldGoalsMade","fieldGoalsAttempted","threePointersMade","threePointersAttempted",
                          "freeThrowsMade","freeThrowsAttempted","plusMinus","didNotPlay","notPlayingReason"]
          team_cols = ["gameId","teamId","teamTricode","teamCity","teamName","opponentTeamId","home","win",
                       "points","reboundsTotal","assists","steals","blocks","turnovers",
                       "fieldGoalsMade","fieldGoalsAttempted","threePointersMade","threePointersAttempted",
                       "freeThrowsMade","freeThrowsAttempted"]
          ensure('export/games.csv', games_cols)
          ensure('export/player_stats.csv', players_cols)
          ensure('export/team_stats.csv', team_cols)
          PY

      - name: Ingest latest NBA data (yesterday + today by default)
        env:
          USE_PARQUET: "0"
          # Optional one-off backfill examples (uncomment one):
          # START_DATE: "2025-01-10"
          # END_DATE:   "2025-01-17"
          # DAYS_BACK:  "30"
        run: |
          set -euxo pipefail
          python src/ingest.py
          echo "Preview files:"
          ls -lh export || true
          head -n 5 export/games.csv || true
          head -n 5 export/team_stats.csv || true
          head -n 5 export/player_stats.csv || true

      - name: Patch dataset owner in metadata to your Kaggle handle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        run: |
          set -euxo pipefail
          sed -i -E "s/\"id\": \"[^\"]*\\/nba-daily-updates\"/\"id\": \"${KAGGLE_USERNAME//\//\\/}\\/nba-daily-updates\"/g" dataset-metadata.json
          echo "metadata:"
          cat dataset-metadata.json

      - name: Configure Kaggle CLI credentials
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          set -euxo pipefail
          mkdir -p ~/.kaggle
          printf '{"username":"%s","key":"%s"}\n' "$KAGGLE_USERNAME" "$KAGGLE_KEY" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          kaggle --version
          kaggle datasets list -p 1 >/dev/null

      - name: Create or version Kaggle dataset
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        run: |
          set -euxo pipefail
          DS="${KAGGLE_USERNAME}/nba-daily-updates"
          if kaggle datasets status "$DS" >/dev/null 2>&1; then
            echo "Dataset exists; versioning…"
            kaggle datasets version -p . -m "Daily update" -r zip --dir-mode zip
          else
            echo "Dataset missing; creating…"
            kaggle datasets create -p .
          fi

      - name: Show Kaggle dataset URL
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        run: echo "https://www.kaggle.com/datasets/$KAGGLE_USERNAME/nba-daily-updates"
